修復cahce login 的問題#74
NKUST-ITC/AP-API pull request #75
Opened 2019-06-28 06:10 UTC by takidog

如題

cache login 會檢查redis 是否有cookie
cookie 失效時間設定為600秒

2019-06-28 12:49 UTC, abc873693 approved these changes

2019-06-28 13:19 UTC, mlouielu requested changes
Some issue need to be fixed and clarify

2019-06-28 13:19 UTC, mlouielu commented on src/kuas_api/kuas/cache.py
> +red_auth = redis.StrictRedis.from_url(
I don't get it, what is the different between `red` and `red_auth`?

2019-06-28 13:19 UTC, mlouielu commented on src/kuas_api/kuas/cache.py
> +
remove duplicate blank line

2019-06-28 13:19 UTC, mlouielu commented on src/kuas_api/kuas/cache.py
> +        login_json = json.loads(user_redis_cookie)
`return json.loads(user_redis_cookies)`

2019-06-28 13:19 UTC, mlouielu commented on src/kuas_api/kuas/cache.py
> +        user_redis_cookie = red_auth.get(username)
cookie -> cookies

2019-06-28 13:19 UTC, mlouielu commented on src/kuas_api/kuas/cache.py
> +red_auth = redis.StrictRedis.from_url(
Why don't use use `red`?

2019-06-28 13:21 UTC, takidog commented on src/kuas_api/kuas/cache.py
> +red_auth = redis.StrictRedis.from_url(
這次為了減少更動，當初存cookie存入redis沒有設定編碼(存bytes)，導致把資料拿出來又要經過一波轉碼的過程，個人認為轉碼應該在redis上就做好，不應該撈出來再轉

2019-06-28 13:22 UTC, takidog commented on src/kuas_api/kuas/cache.py
> +        login_json = json.loads(user_redis_cookie)
了解

2019-06-28 14:16 UTC, abc873693 approved these changes

2019-06-28 14:22 UTC, mlouielu commented on src/kuas_api/kuas/cache.py
> +red_auth = redis.StrictRedis.from_url(
If so, then it should be a separate PR, and it should not deal in this one.

2019-06-28 14:32 UTC, takidog commented on src/kuas_api/kuas/cache.py
> +red_auth = redis.StrictRedis.from_url(
我認為還是在同一個問題中，我並沒有要處理其他舊有的code存入redis是bytes的問題，我而外開了一個是已經會編碼的redis連接只處理cache login 沒檢查cache的事情

當然如果還是覺得有問題
也是能繼續用`red` 去連線，也只是讀入時要再額外編碼就是

2019-06-28 14:38 UTC, abc873693 commented on src/kuas_api/kuas/cache.py
> +red_auth = redis.StrictRedis.from_url(
But @takidog  think this problem login cache is server delay main reason in this weeks.
At same time v3 api is developing, and request will down in next week.
I prefer change in v3 api.

2019-06-28 14:47 UTC, abc873693 commented on src/kuas_api/kuas/cache.py
> +red_auth = redis.StrictRedis.from_url(
@takidog  this problem need open issue to tracking

2019-06-28 15:06 UTC, mlouielu commented on src/kuas_api/kuas/cache.py
> +red_auth = redis.StrictRedis.from_url(
Please add comment on that line to express your idea, otherwise others will get the same confused I got

2019-06-29 02:10 UTC, takidog commented on src/kuas_api/kuas/cache.py
> +red_auth = redis.StrictRedis.from_url(
已補

2019-07-01 02:10 UTC, vn7n24fzkq approved these changes

2019-07-01 03:37 UTC, merged